export const GET_ALL_USERS = 'chat-hub/GET_ALL_USERS'
export const CREATE_USER = 'chat-hub/CREATE_USER'
export const LOGIN_USER = 'chat-hub/LOGIN_USER'
export const CREATE_ERROR = 'chat-hub/CREATE_ERROR'
export const CLEAR_ERROR = 'chat-hub/CLEAR_ERROR'
export const LOGOUT = 'chat-hub/LOGOUT'
